services:
  backend:
    image: subodhsingh20/nova-ai-backend:latest
    container_name: nova-ai-backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: subodhsingh20/nova-ai-frontend:latest
    container_name: nova-ai-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
