services:
  backend:
    image: subodhsingh20/nexusai-backend:latest
    container_name: nexusai-backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: subodhsingh20/nexusai-frontend:latest
    container_name: nexusai-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
