name: CI/CD Pipeline with IBM Notifications

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy
        run: npm run deploy

      - name: Notify Success
        if: success()
        run: |
          curl -X POST "https://${{ secrets.au-syd}}.event-notifications.cloud.ibm.com/event-notifications/v1/instances/${{ secrets.IBM_EN_INSTANCE_ID }}/notifications" \
          -H "Authorization: Bearer ${{ secrets.prcuNduufLgOKB1IIVGoG7AJvh2WV4dyZjoJ9EP8wlLf}}" \
          -H "Content-Type: application/json" \
          -d '{
            "specversion": "1.0",
            "type": "cicd.success",
            "source": "github-actions",
            "subject": "CI/CD Pipeline Success",
            "data": {
              "message": "Deployment completed successfully for commit $GITHUB_SHA"
            },
            "ibmen": {
              "topic": "event-notifications-for-EADC-project"
            }
          }'

      - name: Notify Failure
        if: failure()
        run: |
          curl -X POST "https://${{ secrets.au-syd}}.event-notifications.cloud.ibm.com/event-notifications/v1/instances/${{ secrets.IBM_EN_INSTANCE_ID }}/notifications" \
          -H "Authorization: Bearer ${{ secrets.prcuNduufLgOKB1IIVGoG7AJvh2WV4dyZjoJ9EP8wlLf}}" \
          -H "Content-Type: application/json" \
          -d '{
            "specversion": "1.0",
            "type": "cicd.failure",
            "source": "github-actions",
            "subject": "CI/CD Pipeline Failure",
            "data": {
              "message": "Pipeline failed for commit $GITHUB_SHA"
            },
            "ibmen": {
              "topic": "event-notifications-for-EADC-project"
            }
          }'